Produktverwaltung/config/routes.rb
Rails.application.routes.draw do
  get "products/index"
  get "products/show"
  get "products/show_details"
  get "products/add"
  post "products/add"
  get "products/modify"
  post "products/modify"
  get "products/delete"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

Produktverwaltung/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Produktverwaltung/app/models/product.rb
class Product < ApplicationRecord
end

Produktverwaltung/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

Produktverwaltung/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    @products = Product.all
  end

  def show_details
    @product = Product.find(params[:id])
  end

  def add
    if request.post?
      Product.create(name: params[:name], product_number: params[:product_number], price: params[:price])
      redirect_to("/products/show")
      end
  end

  def modify
    @product= Product.find(params[:id])
    update_params = {}
    update_params[:name] = params[:name] if params[:name].present?
    update_params[:product_number] = params[:product_number] if params[:product_number].present?
    update_params[:price] = params[:price] if params[:price].present?

    
    redirect_to("/products/show")
    
  end

  def delete
    @product= Product.find(params[:id])
    @product.delete()
    redirect_to("/products/show")
  end

end

Produktverwaltung/app/helpers/application_helper.rb
module ApplicationHelper
end

Produktverwaltung/app/helpers/products_helper.rb
module ProductsHelper
end

Produktverwaltung/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Produktverwaltung" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Produktverwaltung/app/views/products/add.html.erb
<h1>Neues Produkt hinzufügen</h1>

<%= form_with model:@product, local: true do |form| %>
  <div>
    <%= form.label :name, "Name" %>
      <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :product_number, "Produktnummer" %>
      <%= form.text_field :product_number %>
  </div>

  <div>
    <%= form.label :price, "Preis" %>
      <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit "Produkt hinzufügen" %>
  </div>
  <% end %>

Produktverwaltung/app/views/products/delete.html.erb
<h1>Products delete</h1>
<p>Find me in app/views/products/delete.html.erb</p>

Produktverwaltung/app/views/products/modify.html.erb
<h1>Products modify</h1>

Produktverwaltung/app/views/products/show.html.erb
<h1>Products show</h1>

<table>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Preis</th>
      <th>Aktionen</th>
    </tr>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td>
          <%= link_to 'Details', products_show_details_path( :id => product.id) %>
          <%= link_to 'Löschen', products_delete_path(:id => product.id)%>
          <!-- <%= link_to 'Modify', products_modify_path(:id => product.id)%> -->
        </td>
      </tr>
    <% end %>
   
</table>
  
<div>
    <%= link_to 'Add', products_add_path%>
</div>

    

Produktverwaltung/app/views/products/show_details.html.erb
<h1>Productss how_details</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Nummer</th>
    <th>Preis</th>
  </tr>
  <tr>
    <td><%= @product.id %></td>
    <td><%= @product.name %></td>
    <td><%= @product.product_number %></td>
    <td><%= @product.price %></td>
  </tr>
</table>
<div>
  <%= link_to 'Alle Produkte anzeigen', products_show_path%>
</div>